-- Supabase schema for Dental Lab Management
-- Run this in the Supabase SQL editor (or via psql) to create the basic tables.

-- Doctors
CREATE TABLE IF NOT EXISTS public.doctori (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nume TEXT NOT NULL,
  email TEXT,
  telefon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Pacients (patients)
CREATE TABLE IF NOT EXISTS public.pacienti (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nume TEXT NOT NULL,
  id_doctor BIGINT REFERENCES public.doctori(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Products
CREATE TABLE IF NOT EXISTS public.produse (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nume TEXT NOT NULL,
  pret NUMERIC(12,2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Technicians
CREATE TABLE IF NOT EXISTS public.tehnicieni (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nume TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Orders (comenzi)
CREATE TABLE IF NOT EXISTS public.comenzi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_doctor BIGINT REFERENCES public.doctori(id) ON DELETE SET NULL,
  id_pacient BIGINT REFERENCES public.pacienti(id) ON DELETE SET NULL,
  data_start DATE,
  termen_limita DATE,
  reducere NUMERIC(12,2) DEFAULT 0,
  total NUMERIC(12,2) DEFAULT 0,
  data_finalizare TIMESTAMP WITH TIME ZONE,
  status TEXT,
  tehnician TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Join table for order products
CREATE TABLE IF NOT EXISTS public.comanda_produse (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comanda_id BIGINT REFERENCES public.comenzi(id) ON DELETE CASCADE,
  produs_id BIGINT REFERENCES public.produse(id) ON DELETE SET NULL,
  cantitate INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Optional: indexes to speed up lookups
CREATE INDEX IF NOT EXISTS idx_comenzi_doctor ON public.comenzi(id_doctor);
CREATE INDEX IF NOT EXISTS idx_comenzi_pacient ON public.comenzi(id_pacient);
CREATE INDEX IF NOT EXISTS idx_pacienti_doctor ON public.pacienti(id_doctor);
CREATE INDEX IF NOT EXISTS idx_comanda_produse_comanda ON public.comanda_produse(comanda_id);
CREATE INDEX IF NOT EXISTS idx_comanda_produse_produs ON public.comanda_produse(produs_id);

-- Demo users table for local testing / SupabaseDemo component
CREATE TABLE IF NOT EXISTS public.demo_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Sample seed data for demo_users removed — no test rows will be inserted by default

-- Reset identity sequences to avoid duplicate key errors when rows were inserted with explicit IDs.
-- Run these statements if you encounter "duplicate key value violates unique constraint" errors.
SELECT setval(pg_get_serial_sequence('public.comenzi', 'id'), COALESCE((SELECT MAX(id) FROM public.comenzi), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.comanda_produse', 'id'), COALESCE((SELECT MAX(id) FROM public.comanda_produse), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.doctori', 'id'), COALESCE((SELECT MAX(id) FROM public.doctori), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.pacienti', 'id'), COALESCE((SELECT MAX(id) FROM public.pacienti), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.produse', 'id'), COALESCE((SELECT MAX(id) FROM public.produse), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.tehnicieni', 'id'), COALESCE((SELECT MAX(id) FROM public.tehnicieni), 0) + 1, false);
